baseURL = "https://elenaterzieva.github.io/elenaterzieva/"
languageCode = "en-us"
title = "My Blog"
theme = "paper"

[params]
  color = "linen"
  github = "YOUR_GITHUB_USERNAME"
  avatar = "https://github.com/elenaterzieva.png"
  name = "Your Name"
  bio = "My blog"
