baseURL = "https://elenaterzieva.github.io/elenaterzieva/"
languageCode = "en-us"
title = "Ellie's Log"
theme = "paper"

[params]
  color = "linen"
  github = "YOUR_GITHUB_USERNAME"
  name = "Ellie's Log"
  bio = "Ellie's Log"
